### ISSUE TITLE
py.typed needed for PEP 561 compatibility

### ISSUE THREAD

**Issue by danygielow** [sqids/sqids-python#11]
Hi,

to be able to use the type hints with mypy, you have to add a py.typed file to the package to make it PEP 561 compatible.
I tried to fork the project and tried multiple things to get py.typed into the built package, but somehow I can't do it.

I have also not worked with setuptools for a long time.

https://peps.python.org/pep-0561/
https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
https://setuptools.pypa.io/en/latest/userguide/datafiles.html

Thank you

**Comment by Pevtrick** [comment]
I have already thought about transferring the sqids module into a package and the constants into an extra module. In the course of this a `py.typed` file can be added.

**Comment by Pevtrick** [comment]
Added compatibility in 0318361f76cf2e20a6521a56ce248cb816cbc0bc
