### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by Pevtrick** [sqids/sqids-python#12]
Create a new release and publish it on PyPI to incorporate new features.

**Comment by 4kimov** [comment]
@Pevtrick will do, any chance you could update the changelog with the changes before I push?

**Comment by Pevtrick** [comment]
Done in 9159badbcb4e9c141fe73a8264d345b6527e0879

**Comment by 4kimov** [comment]
Thank you @Pevtrick. Published + invited you to PyPI
