### ISSUE TITLE
Can it be made available for py 3.6?

### ISSUE THREAD

**Issue by zehawki** [sqids/sqids-python#13]
Currently says:

Requires: Python >=3.8

on https://pypi.org/project/sqids/

**Comment by zehawki** [comment]
Further I did the following:

`pip install --ignore-requires-python sqids --upgrade`

which gives me an error of `TypeError: sum() takes no keyword arguments` at `start=len(numbers)` in sqids.py", line 62, in __encode_numbers. 

I understand that "start as a keyword was added to the sum() function in Python 3.8" according to this https://github.com/jeremyephron/simplegmail/issues/21#issuecomment-749994392, but I'm not able to corroborate this in python docs itself. I did find this https://stackoverflow.com/questions/53877574/does-python-3-6-sum-have-start-0-keyword-argument

Next I tested a small piece of code on online Py 3.6 and there's no issue:

num_tuples = ((1, 2, 3, 4, 5, 6))
print(sum(num_tuples, start=(100)))

on https://pythononlineeditor.com/python-online-editor-36/#! and https://pyonlinecompiler.com/py-online-compiler-36/, and they work fine.

So now I'm quite puzzled as to whats going on.

**Comment by Pevtrick** [comment]
I don't see a problem with this, but I suggest a different solution. Which also makes the code a little more readable.

```python
        offset = sum(
            (
                ord(self.__alphabet[v % len(self.__alphabet)]) + i
                for i, v in enumerate(numbers)
            )
        )
        offset = (offset + len(numbers)) % len(self.__alphabet)
```

@4kimov Should the package be marked as Python 3.6 compatible in PyPI? Python 3.6 has been in Eol status for almost 2 years.

**Comment by 4kimov** [comment]
@Pevtrick We've had similar discussions for [PHP](https://github.com/sqids/sqids-php/issues/4) and [Go](https://github.com/sqids/sqids-go/issues/4).

My personal opinion is if it doesn't hold back progress / development and an easy fix, then why not make devs' lives easier by supporting. But I leave it up to your best judgement.

**Comment by Pevtrick** [comment]
Added Python 3.6 support in dfa94c200de766f7867a4050504e566ee44d3184
New Version on PyPI will follow soon.

**Comment by Pevtrick** [comment]
New Release is available on PyPI now. @4kimov Would you add tags in the GitHub repository for v0.4.0 and the new v0.4.1?

**Comment by 4kimov** [comment]
@Pevtrick done, thank you 💪
