### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by franklsf95** [sqids/sqids-python#14]
I love sqids and am using it in my Django project. However I notice this implementation is in pure Python. Have we considered using a C extension or a Rust extension? Has anyone done performance comparisons of the various sqid implementations?

**Comment by 4kimov** [comment]
Hi @franklsf95, was this issue meant for some other repo upstream that might be using Sqids?

**Comment by franklsf95** [comment]
@4kimov No, I'm thinking about using squid's in my own project, and I'm just wondering about its performance.

**Comment by 4kimov** [comment]
@franklsf95 I see. I am not aware of any performance comparison between libs, but might be an interesting read.

Individual repos are written in their respective languages for simplicity and wider support. If you're optimizing for speed, [C](https://github.com/sqids/sqids-c) and [Rust](https://github.com/sqids/sqids-rust) repos are of course available (as standalone libs). Most latency is usually I/O-bound in apps, so might be an overkill to optimize this encoding library.
