### ISSUE TITLE
Use dunder prefix convention to mark methods and attributes as private

### ISSUE THREAD

**Issue by Pevtrick** [sqids/sqids-python#4]
The Python implementation should follow the reference implementation and implement private methods and attributes as such using the appropriate mechanisms.

If this is a desired extension, I would provide the implementation for it.

**Comment by 4kimov** [comment]
Same as #3, could use some PRs to fix whatever needs adjusting 👍

**Comment by 4kimov** [comment]
https://github.com/sqids/sqids-python/pull/8
